config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'
  devise_for :users, controllers: { registrations: 'users/registrations'}
  root to: 'rides#index'

  get 'search', to: "rides#index"

  resources :rides, only: [:index, :new, :create, :show, :destroy], shallow: true do
    resources :reservations, only: [:index, :new, :create, :show]
  end

  resources :reservations, only: [:destroy]

  resources :users, only: [] do
    member do
      get :my_rides
      get :my_reservations
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :reservations, dependent: :destroy
  has_many :rides, dependent: :destroy

  has_one_attached :photo

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, :password, presence: true

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile
    @user = current_user
  end

  def my_rides
    @user = current_user
    @rides = @user.rides
  end

  def my_reservations
    @user = current_user
    @reservations = @user.reservations
  end

  private

  def article_params
    params.require(:user).permit(:last_name, :first_name, :photo)
  end

end

app/views/users/my_reservations.html.erb
<div class="container">
  <div class="row justify-content-center align-items-center">
    <p class="text-right link-to"><%= link_to "Back to home page", rides_path %></p>
    <div class="col-xs-12 col-sm-8 col-md-6">
      <h3 class="text-center mb-4 mt-3">Your reservations</h3>
      <% @reservations.each do |reservation| %>
        <%= render 'shared/reminder_reservations', reservation: reservation %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/my_rides.html.erb
<div class="row justify-content-center align-items-center">
  <div class="container">
    <p class="text-right link-to"><%= link_to "Back to home page", rides_path %></p>
    <div class="col-xs-12 col-sm-8 col-md-6">
      <h3 class="text-center mb-4 mt-3">Your rides</h3>
      <% @rides.each do |ride| %>
        <%= render 'shared/reminder_user_rides', ride: ride %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<div class="container">
  <div class="row justify-content-center align-items-center">
    <div class="col-xs-12 col-sm-8 col-md-6">
      <%= simple_form_for @user, url: user_registration_path do |f| %>
        <div class="row-2 mb-4">
          <div class="photo-bloc">
            <div class="d-flex flex-column align-items-center text-center ml-5">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag(current_user.photo.key, class: "avatar-profile-page") %>
              <% else %>
                <%= image_tag 'logo.jpg', class: "avatar-profile-page" %>
              <% end %>
              <span class=""id='name-user'></span>
              <span class="" id='email-user'></span>
              <%= f.input :photo, as: :file, class:"btn btn-outline-dark detail" %>
              <span></span>
            </div>
          </div>
            <div class="">
              <div class="mt-3">
                <div class="text-center">
                  <h4>My informations</h4>
                </div>
                <div class="row-2">
                  <div class="col">
                    <%= f.input :first_name, label: "First name", placeholder: 'First name', value: @user.first_name %>
                  </div>
                  <div class="col">
                    <%= f.input :last_name, label: "Last name", placeholder: 'Last name', value: @user.last_name %>
                  </div>
                </div>
                <div class="row-2">
                  <div class="col">
                    <%= f.input :email, label: "Email", placeholder: 'Your email', value: @user.email %>
                  </div>
                </div>
              </div>
            </div>
            <div class="">
                <h4 class="text-left">Password</h4>

                <div class="row-2">
                  <div class="col">
                    <div class="form-group">
                        <%= f.input :current_password, label: "Current password", placeholder: '••••••', value: @user.password %>
                    </div>
                  </div>
                </div>
                <div class="row-2">
                  <div class="col">
                    <div class="form-group">
                        <%= f.input :password, label: "New password", placeholder: '••••••', value: @user.password %>
                    </div>
                  </div>
                </div>
                <div class="row-2">
                  <div class="col">
                    <div class="form-group">
                        <%= f.input :password_confirmation, label: "Confirmation", placeholder: '••••••', value: @user.password %>
                    </div>
                  </div>
                </div>
                <div class="text-right mr-2">
                  <%= f.button :submit, 'Submit',class: "mr-2 mt-3 btn btn-outline-dark detail", id: "btn-profile" %>
                </div>
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>