config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'
  devise_for :users, controllers: { registrations: 'users/registrations'}
  root to: 'rides#index'

  get 'search', to: "rides#index"

  resources :rides, only: [:index, :new, :create, :show, :destroy], shallow: true do
    resources :reservations, only: [:index, :new, :create, :show]
  end

  resources :reservations, only: [:destroy]

  resources :users, only: [] do
    member do
      get :my_rides
      get :my_reservations
    end
  end

end

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="container">
    <div class="banner-search">
      <h1>Going somewhere?</h1>
      <p>Your pick of rides at low prices</p>

          <div class="search-bar">
            <div class="search-bar__search-icon"><i class="fas fa-search"></i></div>
            <div class="search-bar__search-input">
              <form action="/search">
                <input id="search-input__trigger" name="query" type="text" placeholder="Search then enter"/>
              </form>
            </div>
            <div class="search-bar__close-icon"><i class="far fa-times-circle"></i></div>
          </div>

    </div>
    <div class="banner-chevron">
      <i class="fas fa-chevron-down"></i>
    </div>
  </div>
</div>

app/views/shared/_card.html.erb
<%= button_to(ride_path(ride), method: :get, class: "") do %>
  <div class="card-ride">
    <div class="card-photo-part">
      <% if ride.photo.attached? %>
        <%= cl_image_tag("#{ride.photo.key}", crop: :fill, class: "card-photo") %>
      <% else %>
        <%= image_tag 'https://i.picsum.photos/id/1071/3000/1996.jpg?hmac=rPo94Qr1Ffb657k6R7c9Zmfgs4wc4c1mNFz7ND23KnQ', crop: :fill, class: "card-photo" %>
      <% end %>
    </div>
    <div class="card-body-part">
      <div class="card-body">
      <div class="d-flex justify-content-between">
        <h5 class="card-title m-0"><%= ride.pickup_location %> - <%= ride.checkout_location %></h5>
        <h5 class="card-title m-0"><%= ride.rental_rate %> €</h5>
      </div>
        <p class="card-title m-0"><%= ride.pickup_datetime.strftime("%a") %>. <%= ride.pickup_datetime.strftime("%m") %>/<%= ride.pickup_datetime.strftime("%y") %> - with <%= ride.user.first_name %></p>
        <p><%= ride.passengers_update %> / <%= ride.passengers %> Seat left</p>
      </div>
      <div class="card-button">
        <div class="card-user-avatar">
          <% if ride.user.photo.attached? %>
            <%= cl_image_tag ride.user.photo.key, class: "avatar", height: 50, width: 50, crop: :fill %>
          <% else %>
            <%= image_tag "logo.jpg", class: "avatar", height: 50, width: 50, crop: :fill %>
          <% end %>
        </div>
        <p><i class="fas fa-star"></i> 4.6<%#= ride.user.rating %></p>
        <%= link_to 'Book this ride', new_ride_reservation_path(ride), class:"btn btn-outline-dark detail"%>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-infos">
    <div class="footer-components">
      <p>Proin ac porta mauris. Mauris eu quam nec risus porttitor luctus a sed magna. Nulla vel lorem ullamcorper.</p>
    </div>
    <div class="footer-components">
      <p>Proin ac porta mauris. Mauris eu quam nec risus porttitor luctus a sed magna.</p>
    </div>
    <div class="footer-components">
      <p>Proin ac porta mauris. Mauris eu quam. Nulla vel lorem ullamcorper</p>
    </div>
    <div class="footer-links">
      <a href="https://www.instagram.com/?hl=fr" target="_blank"><i class="fab fa-instagram"></i></a>
      <a href="https://fr-fr.facebook.com/"><i class="fab fa-facebook" target="_blank"></i></a>
      <a href="https://twitter.com/?lang=fr"><i class="fab fa-twitter" target="_blank"></i></a>
    </div>
  </div>
  <div class="footer-copyright">
    <p>© 2021 - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac egestas tellus. Donec vel orci in felis ornare finibus. Suspendisse molestie nisl at lacus pulvinar, a imperdiet orci efficitur.</p>
  </div>
</div>

app/views/shared/_modal_passengers.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Passengers</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <form>
            <div class="mb-3">
              <label for="passengers-input" class="col-form-label">How many seats do you want to book?</label>
              <input type="text" class="form-control" id="passengers-input">
            </div>
          </form>
        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <% if ride.passengers >= 1 %>
          <%= link_to 'Book this ride', ride_reservations_path([ride, current_user]), class:"btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="d-flex align-items-center">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "logo.jpg", class: "avatar" %>
    <% end %>
    <h5 id="name">going somewhere</h5>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Search", "/", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <% if user_signed_in? %>
          <div class="d-flex align-items-center">
            <%= link_to "Publish a ride", new_ride_path, class: "nav-link" %>
          </div>
        <% end %>
      </li>
      <li class="nav-item dropdown">
        <% if current_user && current_user.photo.attached? %>
          <%= cl_image_tag(current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
        <% else %>
          <%= image_tag "logo.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <% if user_signed_in? %>
          <%= link_to "My profile",users_profile_path, class: "dropdown-item" %>
          <%= link_to("My rides", my_rides_user_path(current_user), class: "dropdown-item") %>
          <%= link_to("My reservations", my_reservations_user_path(current_user), class: "dropdown-item") %>
          <%= link_to("Log out", destroy_user_session_path, method: :delete, class: "dropdown-item") %>
        <% else %>
          <%= link_to("Sign in", new_user_session_path, class: "dropdown-item") %>
          <%= link_to("Sign up", new_user_registration_path, class: "dropdown-item") %>
        <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_reminder.html.erb
<%= reservations.each do |reservation| %>
  <div class="reminder-container">
    <div class="reminder-informations">
      <img src="" alt="">
      <div class="informations-text">
        <h5><%= reservation.ride.pickup_location %></h5>
        <p class="card-title m-0"><%= reservation.ride.pickup_datetime.strftime("%a") %>. <%= reservation.ride.pickup_datetime.strftime("%m") %>/<%= reservation.ride.pickup_datetime.strftime("%y") %></p>
        <h5><%= reservation.ride.checkout_location %></h5>
      </div>
      <div class="informations-variables">
        <h5><%= reservation.ride.rental_rate %></h5>
        <h6><%= reservation.ride.passengers %></h6>
      </div>
    </div>
    <div class="reminder-footer">
      <img src="" alt="">
      <div class="d-flex">
        <p class="card-title m-0">with <%= reservation.ride.user.first_name %></p>
        <p><i class="fas fa-star"></i> 4.6<%#= ride.user.rating %></p>
      </div>
      <%= link_to(
        reservation_path(reservation),
        method: :delete, remote: true,
        class: "btn btn-outline-dark detail",
        data: { confirm: "Do you want to cancel this reservation?" }
        ) do %>
          <i class="fas fa-trash card-trash">Cancel</i>
        <% end %>
    </div>
  </div>

<% end %>

app/views/shared/_reminder_reservations.html.erb
<div class="reminder-container">
  <div class="reminder-informations">
    <div class="informations-text">
      <h5><%= reservation.ride.pickup_location %></h5>
      <p class="card-title m-0"><%= reservation.ride.pickup_datetime.strftime("%a") %>. <%= reservation.ride.pickup_datetime.strftime("%m") %>/<%= reservation.ride.pickup_datetime.strftime("%y") %></p>
      <h5><%= reservation.ride.checkout_location %></h5>
    </div>
    <div class="informations-variables">
    <h5><%= reservation.ride.rental_rate %> €</h5>
    <h6><%= reservation.ride.passengers %> Passengers</h6>
    </div>
  </div>
  <div class="reminder-footer">
    <div class="reminder-user">
      <% if reservation.ride.user.photo.attached? %>
        <%= cl_image_tag(reservation.ride.user.photo.key, class: "avatar", height: 50, width: 50, crop: :fill) %>
      <% else %>
        <%= image_tag "logo.jpg", class: "avatar", height: 50, width: 50, crop: :fill %>
      <% end %>
      <div class="">
        <p class="card-title m-0">with <%= reservation.ride.user.first_name %></p>
        <p><i class="fas fa-star"></i> 4.6<%#= user.rating %></p>
      </div>
  </div>
    <%= link_to(
      reservation_path(reservation),
      method: :delete, remote: true,
      class: "btn btn-outline-dark detail",
      data: { confirm: "Do you want to cancel this reservation?" }
      ) do %>
        <i class="fas fa-trash card-trash">Cancel</i>
      <% end %>
  </div>
</div>

app/views/shared/_reminder_ride.html.erb
<div class="reminder-container-ride">
  <div class="reminder-informations">
    <div class="informations-text">
      <h5><%= ride.pickup_location %></h5>
      <p class="card-title m-0"><%= ride.pickup_datetime.strftime("%a") %>. <%= ride.pickup_datetime.strftime("%m") %>/<%= ride.pickup_datetime.strftime("%y") %></p>
      <h5><%= ride.checkout_location %></h5>
    </div>
    <div class="informations-variables">
      <h5><%= ride.rental_rate %> €</h5>
      <h6><%= ride.passengers_update %> / <%= ride.passengers %> Seat left</h6>
    </div>
  </div>
  <div class="reminder-footer">
    <div class="reminder-user">
      <% if ride.user.photo.attached? %>
        <%= cl_image_tag ride.user.photo.key, class: "avatar", height: 50, width: 50, crop: :fill %>
      <% else %>
        <%= image_tag "logo.jpg", class: "avatar", height: 50, width: 50, crop: :fill %>
      <% end %>
      <div class="">
        <p class="card-title m-0">with <%= ride.user.first_name %></p>
        <p><i class="fas fa-star"></i> 4.6<%#= user.rating %></p>
      </div>
    </div>
    <!-- Button trigger modal -->
  <button type="button" class="btn btn-outline-dark detail" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Book this ride
  </button>
  <%= render 'shared/modal_passengers', ride: ride %>
  </div>
</div>

app/views/shared/_reminder_user_rides.html.erb
  <div class="reminder-container">
    <div class="reminder-informations">
      <div class="informations-text">
        <h5><%= ride.pickup_location %></h5>
        <p class="card-title m-0"><%= ride.pickup_datetime.strftime("%a") %>. <%= ride.pickup_datetime.strftime("%m") %>/<%= ride.pickup_datetime.strftime("%y") %></p>
        <h5><%= ride.checkout_location %></h5>
      </div>
      <div class="informations-variables">
        <h5><%= ride.rental_rate %> €</h5>
        <h6><%= ride.passengers %> Passengers</h6>
      </div>
    </div>
    <div class="reminder-footer">
      <div class="reminder-user">
        <p class="card-title m-0">Your passengers: </p>
        <% ride.reservations.each do |reservation| %>
          <div class="d-flex justify-content-center align-items-center">
            <% if ride.user.photo.attached? %>
              <%= cl_image_tag ride.user.photo.key, class: "avatar", height: 50, width: 50, crop: :fill %>
            <% else %>
              <%= image_tag "logo.jpg", class: "avatar", height: 50, width: 50, crop: :fill %>
            <% end %>
              <p><%= reservation.user.first_name %></p>
            <% end %>
          </div>
      </div>
      <%= link_to(ride_path(ride),
        method: :delete, remote: true,
        data: { confirm: "Do you want to delete this ride?" } ) do %>
          <button type="button" class="btn btn-outline-dark detail" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Delete
          </button>
        <% end %>
    </div>
  </div>